export enum UserActions {
    SET_ALL_CLIENTS = 'SET_ALL_CLIENTS',
    SET_MODAL = 'SET_MODAL',
    SET_IS_LOGGED = 'SET_IS_LOGGED',
    SET_USER_LOGIN = 'SET_USER_LOGIN',
    SET_CURRENT_CLIENT = 'SET_CURRENT_CLIENT',
    ADD_NEW_CLIENT = 'ADD_NEW_CLIENT',
    UPDATE_CLIENT = 'UPDATE_CLIENT',
    REMOVE_CLIENT = 'REMOVE_CLIENT',
}
