export const FETCH_ALL_CLIENTS = 'FETCH_ALL_CLIENTS';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const ADD_CLIENT = 'ADD_CLIENT';
export const CLEAR_CLIENT = 'CLEAR_CLIENT';
export const CHECK_TOKEN = 'CHECK_TOKEN';
export const FETCH_CURRENT_CLIENT = 'FETCH_CURRENT_CLIENT';
export const EDIT_CLIENT = 'EDIT_CLIENT';
